services:
  postgis:
    image: luislado/glosis-postgis:latest
    container_name: glosis-db
    restart: always
    environment:
      DB_HOST: postgis
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: glosis
      POSTGRES_PASSWORD: glosis
    ports:
      - "5442:5432"
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - glosis-net

  shinyapp:
    image: luislado/glosis-shiny:latest
    container_name: glosis-shiny
    restart: always
    environment:
      USER: shiny
      PASSWORD: shiny
      DB_HOST: postgis
      DB_PORT: 5442
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: glosis
    ports:
      - "3838:3838"
    volumes:
      - ./init-scripts:/srv/shiny-server/init-scripts
    depends_on:
      - postgis
    networks:
      - glosis-net

  mapserver:
    image: camptocamp/mapserver
    container_name: glosis-ws
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./data/mapserver:/etc/mapserver:ro
    depends_on:
      - postgis
    networks:
      - glosis-net

networks:
  glosis-net:
    driver: bridge
    name: glosis-net
