services:

  # API (TODO)

  # Database (PostgreSQL)
  glosis-db:
    container_name: glosis-db
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_DB: glosis
      POSTGRES_USER: glosis
      POSTGRES_PASSWORD: glosis
    ports:
      - "5442:5432"
    volumes:
      - ./glosis-db/pgdata:/var/lib/postgresql/data
    networks:
      - glosis-net

  # Kobo Toolbox
  kobo:
    container_name: kobo
    image: kobotoolbox/kobo:latest
    restart: always
    environment:
      - KOBO_SUPERUSER_PASSWORD=admin
      - KOBO_SUPERUSER_USERNAME=admin
      - POSTGRES_DB=glosis
      - POSTGRES_USER=glosis
      - POSTGRES_PASSWORD=glosis
      - POSTGRES_HOST=glosis-db
      - POSTGRES_PORT=5432
      - KOBO_INITIAL_SUPERUSER_PASSWORD=admin
      - KOBO_INITIAL_SUPERUSER_USERNAME=admin
      - KOBO_DEBUG=true
      - KOBO_DEV_MODE=true
      - KOBO_DEV_MODE_EMAIL=true
      - KOBO_DEV_MODE_EMAIL_DOMAIN=localhost
      - KOBO_DEV_MODE_EMAIL_HOST=localhost
      - KOBO_DEV_MODE_EMAIL_PORT=1025
      - KOBO_DEV_MODE_EMAIL_USERNAME=
      - KOBO_DEV_MODE_EMAIL_PASSWORD=
      - KOBO_DEV_MODE_EMAIL_USE_TLS=false
      - KOBO_DEV_MODE_EMAIL_USE_SSL=false
    ports:
      - "8000:8000"
    volumes:
      - ./kobo:/srv/src/kobo
    depends_on:
      - glosis-db
    networks:
      - glosis-net

  # Metadata (pyCSW)
  glosis-md:
    container_name: glosis-md
    image: geopython/pycsw:latest
    environment:
        PYCSW_SERVER_URL: http://localhost:8001
    ports:
      - 8001:8000
    volumes:
      - ./glosis-md/pycsw.yml:/etc/pycsw/pycsw.yml
      - ./glosis-md/records:/records
    networks:
      - glosis-net

  # Data ingestion tool (Shiny)
  glosis-shiny:
    container_name: glosis-shiny
    image: luislado/glosis-shiny:latest
    restart: always
    environment:
      USER: shiny
      PASSWORD: shiny
      DB_HOST: glosis
      DB_PORT: 5442
      DB_NAME: glosis
      DB_USER: glosis
      DB_PASSWORD: glosis
    ports:
      - "3838:3838"
    volumes:
      - ./glosis-shiny/init-scripts:/srv/shiny-server/init-scripts
    depends_on:
      - glosis-db
    networks:
      - glosis-net

  # Web Mapping (Openlayers)
  glosis-wm:
    container_name: glosis-wm
    build: 
      context: ./glosis-wm
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./glosis-wm/public/layer_info.csv:/usr/share/nginx/html/public/layer_info.csv:ro
    environment:
      - NODE_ENV=production
    networks:
      - glosis-net
    depends_on:
      - glosis-ws

  # Web Services (MapServer)
  glosis-ws:
    container_name: glosis-ws
    image: camptocamp/mapserver:8.4
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./glosis-ws/data:/etc/mapserver:ro
    depends_on:
      - glosis-db
    networks:
      - glosis-net

networks:
  glosis-net:
    driver: bridge
    name: glosis-net
