#!/bin/bash

###############################################
#                    Rename                   #
###############################################

echo

COUNTRY=TH
PROJ=GSNM
YEAR=2025
UD="0"
LD=30
INPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/input/$PROJ"                   # << EDIT THIS LINE!
OUTPUT_DIR="/home/carva014/Downloads/FAO/AFACI/$COUNTRY/tmp"                          # << EDIT THIS LINE!

mkdir -p "$OUTPUT_DIR"

cp $INPUT_DIR/TH-GSNM-AKX-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-GSNM-AKXSD-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UD-$LD-SDEV.tif 
cp $INPUT_DIR/TH-GSNM-APX-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-GSNM-APXSD-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UD-$LD-SDEV.tif 
cp $INPUT_DIR/TH-GSNM-BDX-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-GSNM-BDXSD-2025-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/TH-GSNM-CEC-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-GSNM-CECSD-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UD-$LD-SDEV.tif
cp $INPUT_DIR/TH-GSNM-PHX-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-MEAN.tif
cp $INPUT_DIR/TH-GSNM-PHXSD-2024-0-30.tif $OUTPUT_DIR/$COUNTRY-$PROJ-PHX-$YEAR-$UD-$LD-SDEV.tif
