#!/bin/bash

###############################################
#                    Rename                   #
###############################################


COUNTRY=BT
PROJ=GSOC
YEAR=2022
UD="0"
LD=30
INPUT_DIR="/home/carva014/Work/Code/FAO/GloSIS/glosis-datacube/$COUNTRY/Input/$PROJ"
OUTPUT_DIR="/home/carva014/Work/Code/FAO/GloSIS/glosis-datacube/$COUNTRY/tmp"

cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADBAU-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM1-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM2-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_AbsDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGADSSM3-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAU-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRBAUU-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM1U-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM2U-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_ASR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGASRSSM3U-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_BAU_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAUU-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_BAU_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCBAU-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM1-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM2-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_finalSOC_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSOCSSM3-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RelDiff_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM1-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RelDiff_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM2-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RelDiff_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRDSSM3-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM1_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM1_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM1U-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM2_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM2_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM2U-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM3_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_RSR_SSM3_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGRSRSSM3U-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_SSM_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSSMU-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_T0_Map030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Bhutan_GSOCseq_T0_UncertaintyMap030.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CORGT0U-$YEAR-$UP-$LD.tif


COUNTRY=BT
PROJ=GSNM
YEAR=2024
UD="0"
LD=30
INPUT_DIR="/home/carva014/Work/Code/FAO/GloSIS/glosis-datacube/$COUNTRY/Input/$PROJ"
OUTPUT_DIR="/home/carva014/Work/Code/FAO/GloSIS/glosis-datacube/$COUNTRY/tmp"

cp $INPUT_DIR/AvailK_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KXX-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/AvailK_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KXXSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/AvailP_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PXX-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/AvailP_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PXXSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/BD_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BKD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/BD_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BKDSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/BS_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BASAT-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/BS_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BASATSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Ca_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CAEXC-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Ca_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CAEXCSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/CEC_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CEC-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/CEC_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CECSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/ClayTotal_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CLAY-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/ClayTotal_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CLAYSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/CNRatio_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CNRAT-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/CNRatio_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CNRATSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/CoarMat_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CFRAGF-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/CoarMat_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CFRAGFSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/K_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KEXC-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/K_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-KEXCSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Mg2_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-MGEXC-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Mg2_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-MGEXCSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Na_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXC-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/Na_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NAEXCSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/OC_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CORG-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/OC_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-CORGSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/pHH2O_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PHAQ-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/pHH2O_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-PHAQSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/SandTotal_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SAND-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/SandTotal_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SANDSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/SiltTotal_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SILT-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/SiltTotal_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-SILTSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/TEB_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BSEXC-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/TEB_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-BSEXCSD-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/TotalN_0_30_mean.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NTOT-$YEAR-$UP-$LD.tif
cp $INPUT_DIR/TotalN_0_30_sd.tiff $OUTPUT_DIR/$COUNTRY-$PROJ-NTOTSD-$YEAR-$UP-$LD.tif


COUNTRY=BT
PROJ=OTHER
YEAR=2024
UD="0"
LD=100
INPUT_DIR="/home/carva014/Work/Code/FAO/GloSIS/glosis-datacube/$COUNTRY/Input/$PROJ"
OUTPUT_DIR="/home/carva014/Work/Code/FAO/GloSIS/glosis-datacube/$COUNTRY/tmp"

cp $INPUT_DIR/SoilType_map_10.tif $OUTPUT_DIR/$COUNTRY-$PROJ-CLAWRB-$YEAR-$UP-$LD.tif
