services:
  pycsw-db:
    container_name: pycsw-db
    image: postgis/postgis:12-3.0-alpine
    environment:
      POSTGRES_USER: glosis
      POSTGRES_PASSWORD: glosis
      POSTGRES_DB: pycsw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5437:5432
    networks:
      - pycsw-net
  pycsw:
    container_name: pycsw
    image: geopython/pycsw:latest
    environment:
        PYCSW_SERVER_URL: http://localhost:8001
    ports:
      - 8001:8000
    volumes:
      - ./pycsw.yml:/etc/pycsw/pycsw.yml
      - ./records:/records
    networks:
      - pycsw-net

networks:
  pycsw-net:

volumes:
  db-data: