version: '3'

services:
  glosis-wm:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public/assets:/usr/share/nginx/html/assets
    environment:
      - NODE_ENV=development